---
title: "homework6"
author: "Daniel Ojeranti"
date: "11/24/2020"
output: html_document
---

```{r, setup, echo = F, message = FALSE, warning=FALSE}
library(tidyverse)
library(p8105.datasets)
library(hexbin)
library(rvest)
library(ggridges)
library(patchwork)
knitr::opts_chunk$set(
	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(0817)
```

## Problem 1

```{r, message = FALSE, warning = FALSE}
homi.df =
  read_csv("C:/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Homeowrks/p8105_hw5_do2381/homi-data/homicide-data.csv")


homicide.df =
  read_csv("C:/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Homeowrks/p8105_hw5_do2381/homi-data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city,state,sep = "-"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"
    )
  ) %>% 
   filter(
     victim_race %in% c("White", "Black",)
     city_state != "Tulsa-AL") %>% 
    select(city_state,resolution, victim_age,victim_race,victim_sex)
```


Start with one city

```{r}
homicide.df %>% 
  filter(city_state == "Baltimore, MD") %>% 
glm(resolution = victim age + victim_race + victim_sex,
    data = baltimore.df,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term,OR,starts_with("CI")) %>% 
  

```

Try across cities

```{r}
models.results.df =
  homicide.df %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = map(.x = data, ~glm(resolution ~ victim_age + victim_race + victim_sex, data =.x, family = binomial())),
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state,results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI"))
    
  )
```


```{r}
models.results.df %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) +
  theme(axis.test.x = element_text(angle = 90, hjust = 1))
  

```

# Problem 2

Find residuals

```{r}

#data cleaning of variables first

baby_df = read_csv("./data/birthweight.csv")
```

fit a model

```{r}

#make scatterplot

model_fit = lm(bwt ~ gaweeks, data = baby_df)
```

```{r}
baby_df %>% 
  modelr::add_residuals(model_fits) %>% 
  ggplot(aes(x =))
```


# Problem 3

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

