---
title: "homework6"
author: "Daniel Ojeranti"
date: "11/24/2020"
output: html_document
---

```{r, setup, echo = F, message = FALSE, warning=FALSE}
library(tidyverse)
library(p8105.datasets)
library(hexbin)
library(httr)
library(rvest)
library(modelr)
library(mgcv)
library(ggridges)
library(patchwork)
knitr::opts_chunk$set(
	fig.width = 6, 
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

set.seed(0817)
```

## Problem 1

```{r, message = FALSE, warning = FALSE}
homi.df =
  read_csv("C:/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Homeowrks/p8105_hw6_do2381/data/homicide-data.csv")


homicide.df =
  read_csv("C:/Users/danie/Documents/Columbia Semester 1 Files/Data Science  R Code/Homeowrks/p8105_hw6_do2381/data/homicide-data.csv") %>% 
  mutate(
    city_state = str_c(city,state,sep = "-"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest"        ~ "unsolved",
      disposition == "Closed by arrest"      ~ "solved"),
    resolved = as.factor(resolved),
    victim_age = as.numeric(victim_age),
  ) %>% 
   filter(
     victim_race %in% c("White", "Black"),
     city_state != "Tulsa-AL",) %>% 
    select(city_state, resolved, victim_age, victim_race, victim_sex)
```


Start with one city

```{r}
baltimore.df = 
  homicide.df %>% 
  filter(city_state == "Baltimore-MD")


glm(resolved ~ victim_age + victim_race + victim_sex, 
    data = baltimore.df,
    family = binomial()) %>% 
  broom::tidy() %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(term,OR,starts_with("CI")) %>% 
  knitr::kable(digits = 3)
  

```

Try across cities

```{r}
models.results.df =
  homicide.df %>% 
  nest(data = -city_state) %>% 
  mutate(
    models = map(.x = data, ~glm(resolved ~ victim_age + victim_race + victim_sex, data =.x, family = binomial())),
    results = map(models, broom::tidy)
  ) %>% 
  select(city_state,results) %>% 
  unnest(results) %>% 
  mutate(
    OR = exp(estimate),
    CI_lower = exp(estimate - 1.96 * std.error),
    CI_upper = exp(estimate + 1.96 * std.error)
  ) %>% 
  select(city_state, term, OR, starts_with("CI"))
    
```


```{r}
models.results.df %>% 
  filter(term == "victim_sexMale") %>% 
  mutate(city_state = fct_reorder(city_state, OR)) %>% 
  ggplot(aes(x = city_state, y = OR)) +
  geom_point() +
  geom_errorbar(aes(ymin = CI_lower, ymax = CI_upper)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
  

```

# Problem 2

Find residuals

```{r}
baby.df = read_csv("./data/birthweight.csv") %>% 
  mutate(babysex = recode(babysex, `1` = "male", `2` = "female"),
         babysex = as.factor(babysex),
         frace = recode(frace, `1` = "white", `2` = "black", `3` = "asian", `4` = "puerto rican", `8` = "other", `9` = "unknown"),
         malform = as.factor(malform))

```

Fit a model

```{r}

#Hypothesized Linear Model

# For this model I decided to include the baby length as predictor of birth weight because in studies it is shown that length and weight are positively correlated. I decided to include baby head circumference as a predictor because I hypothesize that a greater head circumference will yield a greater weight. I included gestational age in my analysis due to previous research and knowledge. Finally, I decided to include the smoke variable because I suspect an inverse relationship between the two variables. Based on prior knowledge and research, smoking status has been shown to have an effect on child birth weight. 

hypo.df = lm(bwt~ blength + bhead + gaweeks + smoken, data = baby.df)
summary(hypo.df)

plot.hypo = baby.df %>% 
  select(bwt,blength,bhead,gaweeks,smoken)

round(cor(plot.hypo),3)
pairs(plot.hypo)

baby.df %>% 
  modelr::add_residuals(hypo.df) %>% 
  modelr::add_predictions(hypo.df) %>% 
  select(resid,pred, everything()) %>% 
  ggplot(aes(x = pred, y = resid)) + 
  geom_point()

# Model 2

model.2 = lm(bwt ~ gaweeks + blength , data = baby.df)
summary(model.2)

# Model 3

model.3 = lm(bwt~blength + bhead + babysex + blength*bhead + blength*babysex + bhead*babysex + blength*bhead*babysex , data = baby.df)
summary(model.3)




```


```{r}

cv.df =
  crossv_mc(baby.df, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble)) 

cv_df = 
  cv.df %>% 
  mutate(
   hypo.df.fit = map(.x = train, ~ lm(bwt ~ blength + bhead + gaweeks + smoken, data = .x)),
   model.2.fit = map(.x = train, ~ lm(bwt ~ gaweeks + blength , data = .x)),
   model.3.fit = map(.x = train, ~ lm(bwt ~ blength + bhead + babysex + blength*bhead + blength*babysex + bhead*babysex + blength*bhead*babysex , data = .x))) %>% 
  mutate(
    rmse_hypo = map2_dbl( hypo.df.fit, test, ~rmse(model = .x, data = .y)),
    rmse_mod1   = map2_dbl(model.2.fit, test, ~rmse(model = .x, data = .y)),
    rmse_mod2 = map2_dbl(model.3.fit, test, ~rmse(model = .x, data = .y)))

cv_df %>% 
  select(starts_with("rmse")) %>% 
  pivot_longer(
    everything(),
    names_to = "model", 
    values_to = "rmse",
    names_prefix = "rmse_") %>% 
  mutate(model = fct_inorder(model)) %>% 
  ggplot(aes(x = model, y = rmse)) + geom_violin()

# Among the 3 models used to predict birth weight, my hypothesized model fits it the best


```



# Problem 3

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

